### PR TITLE
Fix encoding of username when it is an email address

### PR DESCRIPTION
**Pull request by gregschibsted**

### CODE REVIEW

**Comment by gregschibsted** [comment]
@ketan as the most recent commiter here, I wonder if you'd mind taking a look?

**Comment by ketan** [comment]
I've asked @kritika-singh3 to take a look at this and get back to you.

**Comment by kritika-singh3** [comment]
@gregschibsted 
This looks fine to me. Can you please rebase the PR?
Once the PR build goes green, it can be merged.

**Comment by gregschibsted** [comment]
I can't see why the build is failing, could you help me understand what the issue is?

**Comment by kritika-singh3** [comment]
@gregschibsted Looking into it

**Comment by alxtgda** [comment]
Hi! I'm very interested on having this fix on my GoCD server. Can you tell me what is your release process to have this change running ?

**Comment by kritika-singh3** [comment]
> Hi! I'm very interested on having this fix on my GoCD server. Can you tell me what is your release process to have this change running ?

@alxtgda You can download the latest plugin jar from the [releases](https://github.com/gocd/gocd-yum-repository-poller-plugin/releases) and place in `server/plugins/bundled`. Delete the old jar.

Please note this is not a suggested approach as whenever you upgrade the GoCD server, the plugin will get replaced with the plugin that is being bundled with the target GoCD version.

E.g. if you are on 18.12.0, and upgrade it to 19.3.0, the plugin will now be of version `2.0.3`.

**Pull request merged**
